# Generated by Django 4.2.20 on 2025-04-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RTCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_number', models.CharField(max_length=10)),
                ('surnoc', models.CharField(blank=True, max_length=10, null=True)),
                ('hissa', models.CharField(max_length=5)),
                ('village', models.CharField(max_length=100)),
                ('hobli', models.CharField(max_length=100)),
                ('taluk', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('owner_name', models.TextField()),
                ('document', models.FileField(upload_to='rtcs/')),
                ('extracted', models.BooleanField(default=False)),
            ],
        ),
    ]
