# Generated by Django 4.2.20 on 2025-05-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtcrecord',
            name='period',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='rtcrecord',
            name='hissa',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='rtcrecord',
            name='survey_number',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
