# Generated by Django 4.2.20 on 2025-05-01 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RTC', '0002_rtcrecord_period_alter_rtcrecord_hissa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtcrecord',
            name='hissa',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='rtcrecord',
            name='period',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rtcrecord',
            name='survey_number',
            field=models.IntegerField(default=''),
        ),
    ]
