# Generated by Django 4.2.20 on 2025-05-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTC', '0004_alter_rtcrecord_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtcrecord',
            name='owner_name',
            field=models.TextField(default=''),
        ),
    ]
