# Generated by Django 4.2.20 on 2025-05-01 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTC', '0005_alter_rtcrecord_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtcrecord',
            name='period',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
