# Generated by Django 4.2.20 on 2025-05-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTC', '0006_alter_rtcrecord_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtcrecord',
            name='period',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
