# Generated by Django 4.2.20 on 2025-05-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RTC', '0007_alter_rtcrecord_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtcrecord',
            name='period',
        ),
    ]
